[bug] Fix TypeError message for performance report
Instead of failing when comparing reference of different types with
```
TypeError: '>=' not supported between instances of 'str' and 'float'
```
now, ReFrame fails with a much nicer message like
```
cannot compare 9.c with reference value 0
```